site_name: DGS Framework
edit_uri: edit
repo_name: GitHub
repo_url: https://github.com/netflix/dgs-framework
site_url: https://netflix.github.io/dgs/
remote_branch: gh-pages

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Data fetching: datafetching.md
  - Testing: query-execution-testing.md
  - Mutations: mutations.md
  - Code Generation: generating-code-from-schema.md
  - Async Data Fetching: data-loaders.md
  - Error Handling: error-handling.md
  - Examples: examples.md
  - Videos: videos.md
  - Advanced:
    - Using the Platform BOM: advanced/platform-bom.md
    - Nested data fetchers: advanced/context-passing.md
    - Hot reloading schemas: advanced/schema-reloading.md
    - Java GraphQL Client: advanced/java-client.md
    - Security:  advanced/security.md
    - File Uploads: advanced/file-uploads.md
    - Subscriptions: advanced/subscriptions.md
    - Interfaces and Unions: advanced/type-resolvers-for-abstract-types.md
    - Instrumentation (Tracing, Metrics): advanced/instrumentation.md
    - Data Fetching Context: advanced/custom-datafetcher-context.md
    - Federated Testing: advanced/federated-testing.md
    - Dynamic schemas: advanced/dynamic-schemas.md
    - Adding Custom Scalars: scalars.md
    - Mocking: advanced/mocking.md
    - React Example: https://github.com/Netflix/dgs-framework/tree/master/graphql-dgs-example-java

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/dgs_theme.css?v=3.0.13'
extra_javascript:
  - 'js/mermaid.min.js'

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: dgs_theme
  favicon: images/favicon.png
  logo: images/logo--blue.svg
  icon:
    repo: octicons/mark-github-16


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: True
  - footnotes
