site_name: The DGS Framework
edit_uri: edit
repo_name: GitHub
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Testing: query-execution-testing.md
  - Mutations: mutations.md
  - Code Generation: generating-code-from-schema.md
  - Async Data Fetching: data-loaders.md
  - Error Handling: advanced/error-handling.md
  - Advanced:
    - Java GraphQL Client: java-client.md
    - Security:  advanced/security.md
    - File Uploads: advanced/file-uploads.md
    - Subscriptions: advanced/subscriptions.md
    - Interfaces and Unions: advanced/type-resolvers-for-abstract-types.md
    - Data Fetching Context: advanced/custom-datafetcher-context.md
    - Federated Testing: advanced/federated-testing.md
    - Generating Schema from Code: advanced/schema-from-code.md
    - Adding Custom Scalars: scalars.md
    - Mocking: advanced/mocking.md
    - React Example: https://github.com/Netflix/dgs-framework/tree/master/graphql-dgs-example-java
      
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/dgs_theme.css'
extra_javascript:
  - 'js/mermaid.min.js'

theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo--white.svg
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed